variables:
  GIT_STRATEGY: clone

image: node:10-alpine

stages:
  - build
  - test
  - deploy

cache:
  key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
  paths:
    - node_modules/

Build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

  only:
    changes:
      - package-lock.json

  tags:
    - dev-b2b-dev-b2b-staking-devops

# Test:
#   stage: test
#   script:
#     - npm run test

#   tags:
#     - dev-b2b-dev-infinito-staking

Development:
  stage: deploy
  variables:
    ENV: "dev"
    # CI_DEBUG_TRACE: "true"
  environment:
    name: development

  script:
    - RELEASE_DIR=${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}-$(date +%y%m%d%H%M%S)
    - sudo rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --delete-excluded ./ /home/isysadmin/${ENV}-${CI_PROJECT_NAME}/${RELEASE_DIR}
    - sudo chown isysadmin:iblsystem -R /home/isysadmin/${ENV}-${CI_PROJECT_NAME}

    - OLD_RELEASE_DIR=$(readlink -e "/home/isysadmin/${ENV}-${CI_PROJECT_NAME}/current" || echo "NOT EXISTED")
    - sudo su isysadmin -c "ln -sf /home/isysadmin/${ENV}-${CI_PROJECT_NAME}/${RELEASE_DIR} /home/isysadmin/${ENV}-${CI_PROJECT_NAME}/current"
    
    - cd /home/isysadmin/${ENV}-${CI_PROJECT_NAME}/current
    - sudo su isysadmin -c "echo '$DOTENV' > .env"
    - sudo su isysadmin -c "PM2_NAME=$PM2_NAME PM2_INSTANCES=$PM2_INSTANCES PM2_EXEC_MODE=$PM2_EXEC_MODE pm2 start ecosystem.config.js --update-env"
    
    - sudo rm -rf "${OLD_RELEASE_DIR}"

  tags:
    - dev-b2b-dev-infinito-staking



